import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './provider'
import NavbarComponent from '@/components/Layout/Navbar'
import BgLayoutRoot from '@/components/BgLayoutRoot/BgLayoutRoot'
import Footer from '@/components/Layout/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className} >
          <Providers>
            {children}
          </Providers>
      </body>
    </html>
  )
}